version: "3"

services: 
    app:
        build: .
        command: yarn dev
        ports: 
            - '${PORT:-3000}:${PORT:-3000}'
        volumes: 
            - .:/app
        environment: 
            - SECRET=${SECRET}
            - MONGO_URI=mongodb://mongo:27017/api
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        volumes: 
            - .:/data
