version: "3"

services: 
    app:
        build: .
        command: yarn dev
        ports: 
            - '${PORT:-3000}:3000'
        volumes: 
            - .:/app
        environment: 
            - SECRET=${SECRET}
            - MONGO_URI=mongodb://mongo:27017/api
        networks:
         - mongo-compose-network

    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        volumes: 
            - .:/data
        networks:
         - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
